### ISSUE TITLE
Problem for connect with domain name

### ISSUE THREAD

**Issue by CPiersigilli** [Thomaslegravier/SynologySwift#4]
I tried using `SynologySwift` with a public domain, modifying every `http` with `https`, contained in your files, otherwise I would get an error, with this code.
```
import SwiftUI

struct ContentView: View {
    
    let dsInfos = SynologySwiftURLResolver.DSInfos(quickId: "", host: "www.mydomain.it", port: 5001)
    
    var body: some View {
        Button(action: {
            SynologySwift.resolveLogin(dsInfos: self.dsInfos, sessionType: "DownloadStation", login: "myUser", password: "myPassword") { (result) in
                switch result {
                case .success(let authInfos):
                    print(authInfos)
                case .failure(let error):
                    print(error)
                }
            }
        }) {
            Text("Login")
        }
    }
}
```
Unfortunately I got the following error:
`other("An error occured - No such account or incorrect password")`
How can I resolve to get the login?
How can I build the URL to upload a file with your `SynologySwift`?

**Comment by Thomaslegravier** [comment]
Hello Cesare.
First have your get successfully your DSInfos from "SynologySwiftURLResolver.DSInfos" first call ?

**Comment by CPiersigilli** [comment]
I tried using the last version 0.2, without being able to load it from "`Add package dependency ...`", so I copied the `SynologyKit` folder into my app.
The result, without modifying all the `https` in `htpps`, was this:
`2019-12-13 14:57:59.411218+0100 SynologySwift Le Gravier[1359:27168] App Transport Security has blocked a cleartext HTTP (http://) resource load since it is insecure. Temporary exceptions can be configured via your app's Info.plist file.`
I think you should provide for the login the variables indicated in the screen shot below:
<img width="150" alt="Schermata 2019-12-13 alle 15 07 23" src="https://user-images.githubusercontent.com/17962752/70805877-4a8b7f00-1dba-11ea-869a-1d6f4d3c9fb9.png">
The variables indicated above must be used to generate the URL to login Synology NAS:
`https://www.mydomain.cloud:5001/webapi/auth.cgi?api=SYNO.API.Auth&version=3&method=login&account=myaccount&passwd=mypassword&session=FileStation&format=sid`
After logging in, I would like a function that allows me to upload an image as shown on page 63 of the `Synology File Station - Official API` manual.
I am not able, if you are able, I would be happy.

**Comment by Thomaslegravier** [comment]
Hello Cesare,
This error message "App Transport Security has blocked a cleartext HTTP..." is due to app transport security introduce in 2016. Please check this thread for more informations: https://forums.developer.apple.com/thread/6767
