### ISSUE TITLE
Synology Shutdown

### ISSUE THREAD

**Issue by cdebaixo** [Thomaslegravier/SynologySwift#5]
I have an iOS app in which I want to shut down the synology server located in my local network. Can I achieve this with SynologySwift? If not do you have suggestions as to how this can be achieved?
Thanks for your help.

**Comment by Thomaslegravier** [comment]
Hello,

With Synology swift you can get your SID token and use public APIs. I'm sure you can achieve a shut down with public APIs. Try to listen Xhr calls in web browser when you use web dsm client and you will see with API is call.
