### ISSUE TITLE
Two-Factor authentication support

### ISSUE THREAD

**Issue by sgade** [Thomaslegravier/SynologySwift#6]
Hi,

accounts can be secured using Two-Factor authentication methods. On login, a second code is required. The `SYNO.API.Auth` call supports this via the `otp_code` parameter which is passed the short-lived code.

Without the code present, accounts that have 2FA enabled are unable to login. The error is of type: `other("An error occured - 2-step verification code required")`. 

I'd like to see support for 2FA in this library, might even help out myself if you can point me to the place where it needs to be added. Feedback appreciated.

**Comment by Thomaslegravier** [comment]
Hello @sgade,
Sorry I was very busy this past few weeks. 
Yes definitely 2FA support is a very good idea for the next release of SynologySwift ! 
You can check authentication flow in the SynologySwiftAuth.swift class. We need trigger this specific error in the process completion block at line 90. 
Have you some specificities on the 2FA synology flow ? There some API's endpoint to receive 2FA code ?

**Comment by sgade** [comment]
The 2fa flow is similar to the normal login. You just need to pass the one time password from your two-factor app in the call, like so:

<img width="361" alt="image" src="https://user-images.githubusercontent.com/2040657/84882756-01c9c100-b090-11ea-9318-fa9571d7371f.png">

See that last parameter, `otp_code`? That is the crucial part of the request. You cannot request the code as it needs to be generated by a second device of the user.

**Comment by Thomaslegravier** [comment]
Great news ! Thanks for you feedback. 
It will be very easy to support this 2FA code. I will Check that in this few days, keep in touch !

**Comment by Thomaslegravier** [comment]
Hello @sgade ! Good news, otp code param is now available in login method. Sorry for the delay and thank you for you help.

**Comment by Thomaslegravier** [comment]
@sgade could you please test it and give me your feedback please ? Thank you ;)

**Comment by sgade** [comment]
I'm unable to actually test the code. However, the changes look fine. Thank you very much! :)
