### ISSUE TITLE
Tag 0.2 don't resolve with SPM

### ISSUE THREAD

**Issue by VinceBurn** [Thomaslegravier/SynologySwift#8]
Hi, 
I'm making some test using your lib and I faced a problem with Swift Package Manager (SPM) where I was not able to grab version 0.2

The version should be label 0.2.0 in order for SPM to correctly resolve the version. 
I was able to make it work by making a fork and adding a 0.2.1 tag.

**Comment by Thomaslegravier** [comment]
Hello @VinceBurn,
Thank you for your feedback and so sorry for the delay. A new release is now available with tag 0.2.1.
Have a good day,
Thomas.
